### ISSUE TITLE
VPM support

### ISSUE THREAD

**Issue by Silvea12** [LiveDimensions/VRRefAssist#1]
Any chance of setting up a VPM repository for this? Would be fantastic to have this easily installable into new projects this way.

**Comment by LiveDimensions** [comment]
Of course! Next release will also be available as a VPM repository.

Though my recommended method of installation will still be through the .git url since [VRChat has yet to fix their Package Resolver when using source control.](https://github.com/vrchat-community/creator-companion/issues/10)

**Comment by LiveDimensions** [comment]
Done!
https://livedimensions.github.io/LiveDimensions-VRC-Packages/
