### ISSUE TITLE
Import went wrong

### ISSUE THREAD

**Issue by tleylan** [LiveDimensions/VRRefAssist#2]
I downloaded the .unityPackage and attempted to import it. An error occurred and now the project will not start. Can you tell me what files I could edit to stop the project from trying to import this please?

**Comment by tleylan** [comment]
Managed to delete the files by comparing the project files with a backup. Tried the Windows- > Package Manager -> URL and it similarly failed. Now I have to go remove that one as well.

**Comment by LiveDimensions** [comment]
Hello @tleylan , sorry to hear you had issues importing VRRefAssist, do you remember if you saw any errors or did the project not open at all? Also, all of the files are in Packages/VRRefAssist (or Packages/com.livedimensions.vrrefassist if you are viewing them outside of Unity like explorer.)
