### ISSUE TITLE
Option to suppress error messages

### ISSUE THREAD

**Issue by Abbodarr** [LiveDimensions/VRRefAssist#4]
Is there a way to suppress error messages?  I'd like a way to tag, for example, GetComponentInParent should assign null if the component isn't found and not to output an error message to the console.  Currently I can ignore the error messages and the attribute is set to null, but there are enough error messages that it can hide some real issues (unrelated to VRRefAssist).

**Comment by LiveDimensions** [comment]
This is a good suggestion; I think I will add an optional `suppressErrors` bool parameter to autoset attributes.

**Comment by LiveDimensions** [comment]
Added in [v0.0.8](https://github.com/LiveDimensions/VRRefAssist/releases/tag/v0.0.8)!

**Comment by Abbodarr** [comment]
Awesome, thanks!
